project:
  type: book
  output-dir: "../docs"
  
book:
  title: "New Ham Book"
  author: "Rick Gilmore W3TM"
  date: "2024-10-24"
  chapters:
    - index.qmd
    - part: hands-on.qmd
      chapters: 
        - web-sdr.qmd
        - dmr.qmd
        - aprs.qmd
        - satellites.qmd
        - pota-sota.qmd
        - id-signal.qmd
        - find-a-ham.qmd
        - ham-geography.qmd
        - band-conditions.qmd
    - part: gear.qmd
      chapters:
        - planning.qmd
        - portable-station.qmd
        - home-station.qmd
        - mobile-station.qmd
        - remote-station.qmd
    - part: "FCC Regulations"
      chapters:
        - fcc-part-97.qmd
    - part: "Resources"
      chapters:
        - lingo.qmd
    - part: "Exams"
      chapters:
        - technician.qmd

bibliography: include/bib/ham.bib

format:
  html:
    theme: cosmo

