# Planning {-}

## About {-}

Before you spend a dollar, I suggest that you put some time into planning the initial phases of your ham "career".
Your interests will probably change over time, but it's a good idea to start with what excites you about the hobby right now.
Here are some questions to consider.
None of them have either/or answers.

## Questions {-}

- *Where* do you plan to operate?

From home, in your car, or from a portable location like a park or a mountain summit?

- *What mode or modes* do you want to operate in these places?

Voice (SSB or FM), digital modes, or CW?

- *What type(s) of activities* interest you in using these modes?

Special event support, contesting, SOTA/POTA, rag-chewing, nets.

- *Who* do you want to communicate with?

People you don't know (yet) or very specific individuals.

And last, but certainly not the least important:

- *How much* do you have to spend?

In my opinion, the first question, *where* you plan to operate, has the biggest influence on your choices.
So, what follows are three separate chapters relating to setting up a fixed station at-home, operating mobile (from a vehicle), and field or portable operations.

## SPARC-E

Recently, I came up with an acronym to help me remember the components I need to bring when I travel or operate a portable station.
It's a useful mnemonic for me to make sure I've considered the most important categories of equipment.
It applies to planning most ham radio scenarios, and has a memorable pronunciation ("sparky") even if the spelling is a little wonky.

### Support

- How will you support your antenna: a tree, a mast, etc.

### Power

- How will you provide power for your station and accessories?

### Antenna

- What antenna(s) will you bring and for what band(s) and mode(s)?

### Radio

- What radio(s) will you bring and for what band(s) and mode(s)?

### Connectors

- What connectors do you need?
  - Coax for radio $\rightarrow$ antenna
    - Coax connector adapters
  - Power cables
  - USB/serial cables to connect a computer to your radio

### Extras

- Morse key or paddles for [CW](lingo.qmd#cw)
- Microphone for voice
- Computer for digital modes or logging
- Headphones or headset
- Foot switch for [PTT](lingo.qmd#ptt) if not using a hand mic or [VOX](lingo.qmd#vox)
- Antenna analyzer
- Antenna tuner if not using a resonant antenna
- Paper & pencil

