# Quest: POTA/SOTA hunting {- #quest_pota}

## About {-}

In this quest, you will "hunt" hams who are operating using portable stations from one of several thousand parks around the world as part of the Parks on the Air (POTA) system.

## Visit Pota.app {-}

```{r, echo=FALSE, fig.cap="Current Parks on the Air (POTA) from https://pota.app"}
knitr::include_url("https://pota.app/")
```

The site shows hams who are active on the air *right now* and on what frequencies and using which modes.

## Choose a station to "hunt" {-}

By hunt, of course, we mean try to hear on the radio.
Once you're licensed with appropriate privileges, you can try to make contact.
For now, let's just try to hear the station.

You have some decisions to make.
Which mode, CW, FT8, or phone?
Which band?

Unless you have already set up a receiver to copy and decode FT8, you can eliminate stations using [FT8] or [FT4].
Phone is the easiest, but also requires the best band conditions.

Here are some rules of thumb to guide your choices:

1. The lower frequency (higher wavelength) bands (160m, 80m/75m, 60m, and 40m) propagate longer distances at night than during the day. During the early morning hours, 80m/75m might support regional propagation, meaning you can hear stations within several hundred miles of your location. 60m and 40m might also work for regional communication throughout the day.

2. The higher bands (30m, 20m, 17m, 15m, 12m, and 10m) are long distance (DX) bands and are most active during the day and under good solar conditions.

Once you've chosen a station to hunt, you can try to hear them on a WebSDR.

## Open WebSDR {-}

If you pick a WebSDR near your location, then you'll need to consider the rules of thumb above.

If you pick a WebSDR somewhere else, you'll have to think like a ham in one of those locations: What bands are open to hams and to what parts of the world from that location?

Here are some hints:

If it's daytime, try 40m (7.0-7.3 MHz) for regional communications and 20m (14.0-14.35 MHz) for longer distance communications.

## Tune to the POTA station frequency {-}

If the station is still active on the frequency and propagation to the WebSDR location is good, you should see a signal in the waterfall.
Try to copy the station? Can you hear the callsign? Can you hear any stations trying to call.
